<?php
$title = 'Delete ServiceTicket';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($serviceticket->ServiceTicketNo); ?>' by
    '<?php echo $this->escapeHtml($serviceticket->SalesMan); ?>'?
</p>
<?php
$url = $this->url('kristins', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $serviceticket->ServiceTicketNo; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>