<?php
$title = 'My ServiceTicket';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('kristins', array('action'=>'add'));?>">Add new ServiceTicket</a>
</p>

<table class="table">
<tr>
    <th>ServiceTicketNo</th>
    <th>ServiceDate</th>
    <th>SalesMan</th>
        <th>TruckNo</th>
    <th>PaymentTerms</th>
    <th>BillToName</th>
        <th>BillToAddress</th>
    <th>BillToCity</th>
    <th>BillToState</th>
        <th>BillToZip</th>
    <th>BillToContact</th>
    <th>BillToEmail</th>
        <th>ShipToName</th>
    <th>ShipToAddress</th>
    <th>ShipToCity</th>
        <th>&nbsp;</th>
</tr>
<?php 

foreach ($serviceticket as $values) : 

?>
<tr>

    <td><?php echo $this->escapeHtml($values->ServiceTicketNo);?></td>
    <td><?php echo $this->escapeHtml($values->ServiceDate);?></td>
        <td><?php echo $this->escapeHtml($values->SalesMan);?></td>
        <td><?php echo $this->escapeHtml($values->TruckNo);?></td>
    <td><?php echo $this->escapeHtml($values->PaymentTerms);?></td>
        <td><?php echo $this->escapeHtml($values->BillToName);?></td>
    <td><?php echo $this->escapeHtml($values->BillToAddress);?></td>
        <td><?php echo $this->escapeHtml($values->BillToCity);?></td>
    <td><?php echo $this->escapeHtml($values->BillToState);?></td>
        <td><?php echo $this->escapeHtml($values->BillToZip);?></td>
    <td><?php echo $this->escapeHtml($values->BillToContact);?></td>
        <td><?php echo $this->escapeHtml($values->BillToEmail);?></td>
    <td><?php echo $this->escapeHtml($values->ShipToName);?></td>
        <td><?php echo $this->escapeHtml($values->ShipToAddress);?></td>
    <td><?php echo $this->escapeHtml($values->ShipToCity);?></td>
    
    <td>
        <a href="<?php echo $this->url('kristins',
            array('action'=>'edit', 'id' => $values->ServiceTicketNo));?>">Edit</a>
        <a href="<?php echo $this->url('kristins',
            array('action'=>'delete', 'id' => $values->ServiceTicketNo));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>